name: ring deploy
on:
  workflow_dispatch:

jobs:
  ring0-stamp1-su1:
    name: ring0-stamp1-su1
    runs-on: ubuntu-latest
    environment:
      name: ring0.stamp1.su1
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring0-stamp1-su1

  ring0-stamp1-su2:
    name: ring0-stamp1-su2
    runs-on: ubuntu-latest
    needs: ring0-stamp1-su1
    environment:
      name: ring0.stamp1.su2
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring0-stamp1-su2

  ring0-stamp1-su3:
    name: ring0-stamp1-su3
    runs-on: ubuntu-latest
    needs: [ring0-stamp1-su1, ring0-stamp1-su2]
    environment:
      name: ring0.stamp1.su3
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring0-stamp1-su3

  ring0-stamp1-su4:
    name: ring0-stamp1-su4
    runs-on: ubuntu-latest
    needs: [ring0-stamp1-su1, ring0-stamp1-su2, ring0-stamp1-su3]
    environment:
      name: ring0.stamp1.su4
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring0-stamp1-su4

  ring0-stamp1-su5:
    name: ring0-stamp1-su5
    runs-on: ubuntu-latest
    needs:
      [ring0-stamp1-su1, ring0-stamp1-su2, ring0-stamp1-su3, ring0-stamp1-su4]
    environment:
      name: ring0.stamp1.su5
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring0-stamp1-su5

  ring1-stamp1-su1:
    name: ring1-stamp1-su1
    runs-on: ubuntu-latest
    needs: [ring0-stamp1-su5]
    environment:
      name: ring1.stamp1.su1
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring1-stamp1-su1

  ring1-stamp1-su2:
    name: ring1-stamp1-su2
    runs-on: ubuntu-latest
    needs: [ring1-stamp1-su1]
    environment:
      name: ring1.stamp1.su2
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring1-stamp1-su2

  ring1-stamp1-su3:
    name: ring1-stamp1-su3
    runs-on: ubuntu-latest
    needs: [ring1-stamp1-su1, ring1-stamp1-su2]
    environment:
      name: ring1.stamp1.su3
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring1-stamp1-su3

  ring1-stamp1-su4:
    name: ring1-stamp1-su4
    runs-on: ubuntu-latest
    needs: [ring1-stamp1-su1, ring1-stamp1-su2, ring1-stamp1-su3]
    environment:
      name: ring1.stamp1.su4
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring1-stamp1-su4

  ring1-stamp1-su5:
    name: ring1-stamp1-su5
    runs-on: ubuntu-latest
    needs:
      [ring1-stamp1-su1, ring1-stamp1-su2, ring1-stamp1-su3, ring1-stamp1-su4]
    environment:
      name: ring1.stamp1.su5
      url: "https://google.com"
    steps:
      - name: run
        run: echo ring1-stamp1-su5
